### PR TITLE
Image carousel

### PR DESCRIPTION
**Pull request by jonathanraitses**
@nweirant @arfyron I created the component. Any recommendations or comments? :). Sorry for waiting so long!

### CODE REVIEW

**Review by arfyron — COMMENTED** [review]
In your images component. Is there a way to use map or something to render without hardcoding?

**Comment by jonathanraitses** [comment]
I could, but if I do it prevents the same picture from being displayed twice if I add a key (which causes an warning), and as it does the same thing I personally prefer it this way. Though I would change it if you prefer.

**Comment by arfyron** [comment]
I guess I just think that the mapping is probably best practice because it can accommodate any number of images. Ultimately up to you but I bet trent et al would prefer mapping.

Otherwise looks good.

**Comment by jonathanraitses** [comment]
Added your changes.

**Pull request merged**
